# Generated by Django 3.2.8 on 2021-12-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=99, verbose_name='نام کنسرت')),
                ('SingerName', models.CharField(max_length=99, verbose_name='خواننده')),
                ('length', models.IntegerField(verbose_name='زمان')),
                ('Poster', models.ImageField(null=True, upload_to='concertimages/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره')),
                ('Name', models.CharField(max_length=99, verbose_name='مکان')),
                ('Adress', models.CharField(default='تهران -برج میلاد ', max_length=99, verbose_name='آدرس')),
                ('Phone', models.IntegerField(verbose_name='شماره تماس')),
                ('Capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': 'محل برگزاری کنسرت',
                'verbose_name_plural': 'محل برگزاری کنسرت',
            },
        ),
        migrations.CreateModel(
            name='timefieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StarartDateTime', models.DateTimeField(verbose_name='زمان شروع')),
                ('Seat', models.IntegerField(verbose_name='ظرفیت صندلی ')),
                ('status', models.IntegerField(choices=[(1, 'کنسرت در حال شروع شدن است '), (2, 'کنسرت پایان یافته'), (3, 'بلیط ها فروخته شده'), (4, 'کنسرت کنسل شده')], verbose_name='وضعیت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketapp.concertmodel', verbose_name='کنسرت')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketapp.locationmodel', verbose_name='محل برگزاری')),
            ],
            options={
                'verbose_name': 'زمان برگزاری ',
                'verbose_name_plural': 'زمان برگزاری ',
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=99, verbose_name='نام بلیط')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('imageticket', models.ImageField(upload_to='ticketmodel/', verbose_name='تصویر بلیط')),
                ('PorfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.porfilemodel', verbose_name='پروفایل')),
                ('timefieldModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketapp.timefieldmodel', verbose_name='زمان برگزاری')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
