# Generated by Django 3.2.8 on 2021-12-13 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تماس', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
    ]
