# Generated by Django 3.2.8 on 2021-12-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_alter_locationmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='Adress',
            new_name='Address',
        ),
    ]
